services:
  - type: web
    name: zenpt-api
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGODB_URI
        scope: build
      - key: JWT_SECRET
        scope: build
      - key: CLIENT_URL
        value: https://zenpt.netlify.app
        scope: build
      - key: NODE_ENV
        value: production
        scope: build
      - key: PORT
        value: 5000
        scope: build
